compile_and_run:
	javac TestSearchHashLinear.java ; java TestSearchHashLinear
	make clean

compile_and_run_local:
	javac TestSearchHashLinearLocal.java ; java TestSearchHashLinearLocal
	make clean
clean:
	del *.class
